sensitive-word:
  loader-type: REDIS
  config:
    key: sensitive_words

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sensitive_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6666
      password: password
      database: 0