sensitive-word:
  loader-type: MYSQL
  config:
    table: sensitive_words
    columns: word
    conditions:
      is_active: "1"
      type: "prohibited"

spring:
  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-ohj017lr.sql.tencentcdb.com:23186/sensitive_db
    username: root
    password: 8uhb^YJm
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 49.232.228.92
      port: 6666
      password: 8uhb^YJm
      database: 0
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: DEBUG
