sensitive-word:
  console-enabled: true
  loaders:
    txt:
      enabled: true
      filePath: sensitive_words.txt
      delimiter: ','
    json:
      enabled: false
      filePath: sensitive_words.json
  # 默认加载器是否启用（可选）
  default-loader:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sensitive_db
    username: root
    password: 8uhb^YJm
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6666
      password: password
      database: 0

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG